[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'gcc', 'gnumake']

[phases.install]
cmds = [
  'cd client && npm install',
  'cd server && npm install --include=dev --build-from-source'
]

[phases.build]
cmds = [
  'cd client && npm run build',
  'cd server && npm run build'
]

[start]
cmd = 'cd server && node dist/index.js'
