// 8 IT-themed chibi characters for the Mario Party board game

export const CHARACTERS = {
  cody: {
    id: 'cody',
    name: 'Cody',
    title: 'The Code Monkey',
    description: 'Always debugging at 3am. Speaks fluent Stack Overflow.',
    skinColor: '#FDBCB4',
    hairColor: '#704214',
    bodyColor: '#4A90D9',
    pantsColor: '#2C3E50',
    shoeColor: '#1A252F',
    accentColor: '#3A7ABD',
    accessory: 'glasses',
    emoji: '💻',
  },
  haxx: {
    id: 'haxx',
    name: 'Haxx',
    title: 'The Ethical Hacker',
    description: 'Wears a hoodie 24/7. Definitely not hacking anything right now.',
    skinColor: '#D5D8DC',
    hairColor: '#1A1A2E',
    bodyColor: '#2C2C54',
    pantsColor: '#1A1A2E',
    shoeColor: '#0D0D0D',
    accentColor: '#6C3483',
    accessory: 'mask',
    emoji: '🕵️',
  },
  syssy: {
    id: 'syssy',
    name: 'Syssy',
    title: 'The SysAdmin',
    description: 'Has root access to everything. Keeps the servers running on willpower.',
    skinColor: '#FDBCB4',
    hairColor: '#2C3E50',
    bodyColor: '#E67E22',
    pantsColor: '#784212',
    shoeColor: '#4A235A',
    accentColor: '#D35400',
    accessory: 'headset',
    emoji: '🖥️',
  },
  penny: {
    id: 'penny',
    name: 'Penny',
    title: 'The Network Guru',
    description: 'Can subnet in her sleep. Every packet finds its way with her help.',
    skinColor: '#FDBCB4',
    hairColor: '#FFD700',
    bodyColor: '#FF69B4',
    pantsColor: '#C0392B',
    shoeColor: '#922B21',
    accentColor: '#FF1493',
    accessory: 'router',
    emoji: '📡',
  },
  desi: {
    id: 'desi',
    name: 'Desi',
    title: 'The UI Designer',
    description: 'Makes everything beautiful. Judges your UI choices silently.',
    skinColor: '#F4A460',
    hairColor: '#E74C3C',
    bodyColor: '#9B59B6',
    pantsColor: '#6C3483',
    shoeColor: '#4A235A',
    accentColor: '#8E44AD',
    accessory: 'tablet',
    emoji: '🎨',
  },
  quinn: {
    id: 'quinn',
    name: 'Quinn',
    title: 'The Cloud Architect',
    description: 'Lives in the cloud. Refuses to touch physical hardware.',
    skinColor: '#FDBCB4',
    hairColor: '#BDC3C7',
    bodyColor: '#1ABC9C',
    pantsColor: '#0E6655',
    shoeColor: '#0B5345',
    accentColor: '#17A589',
    accessory: 'visor',
    emoji: '☁️',
  },
  rex: {
    id: 'rex',
    name: 'Rex',
    title: 'The Security Guard',
    description: 'Firewall is his personality. No unauthorized access on his watch.',
    skinColor: '#F0D9B5',
    hairColor: '#784212',
    bodyColor: '#27AE60',
    pantsColor: '#1E8449',
    shoeColor: '#145A32',
    accentColor: '#229954',
    accessory: 'badge',
    emoji: '🔒',
  },
  agatha: {
    id: 'agatha',
    name: 'Agatha',
    title: 'The IT Professor',
    description: 'Coded before you were born. Knows COBOL and is proud of it.',
    skinColor: '#FDBCB4',
    hairColor: '#ECF0F1',
    bodyColor: '#8E44AD',
    pantsColor: '#6C3483',
    shoeColor: '#4A235A',
    accentColor: '#7D3C98',
    accessory: 'glasses-professor',
    emoji: '🎓',
  },
};

export const CHARACTERS_ARRAY = Object.values(CHARACTERS);
