// IT-themed multiple-choice questions for the review game
// Add more questions relevant to your course content!

export const QUESTIONS = [
  {
    id: 1,
    category: 'Networking Basics',
    question: 'What does IP stand for?',
    choices: ['Internet Protocol', 'Internal Process', 'Interface Platform', 'Integrated Port'],
    correct: 0,
    difficulty: 'easy',
    coins: 5,
  },
  {
    id: 2,
    category: 'Networking Basics',
    question: 'Which port does HTTP use by default?',
    choices: ['443', '22', '80', '8080'],
    correct: 2,
    difficulty: 'easy',
    coins: 5,
  },
  {
    id: 3,
    category: 'Subnetting',
    question: 'What is the subnet mask for a /24 network?',
    choices: ['255.255.0.0', '255.0.0.0', '255.255.255.0', '255.255.255.128'],
    correct: 2,
    difficulty: 'medium',
    coins: 5,
  },
  {
    id: 4,
    category: 'DNS',
    question: 'What does DNS stand for?',
    choices: ['Data Naming System', 'Domain Name System', 'Dynamic Network Service', 'Digital Node Server'],
    correct: 1,
    difficulty: 'easy',
    coins: 5,
  },
  {
    id: 5,
    category: 'OSI Model',
    question: 'At which OSI layer does TCP operate?',
    choices: ['Layer 2 – Data Link', 'Layer 3 – Network', 'Layer 4 – Transport', 'Layer 5 – Session'],
    correct: 2,
    difficulty: 'medium',
    coins: 5,
  },
  {
    id: 6,
    category: 'Protocols',
    question: 'Which protocol automatically assigns IP addresses to devices?',
    choices: ['DNS', 'FTP', 'DHCP', 'ARP'],
    correct: 2,
    difficulty: 'easy',
    coins: 5,
  },
  {
    id: 7,
    category: 'Security',
    question: 'What does VPN stand for?',
    choices: ['Virtual Private Network', 'Verified Public Node', 'Virtual Packet Network', 'Visible Private Network'],
    correct: 0,
    difficulty: 'easy',
    coins: 5,
  },
  {
    id: 8,
    category: 'Cabling',
    question: 'What is the maximum cable run length for Cat5e/Cat6 Ethernet?',
    choices: ['50 meters', '100 meters', '200 meters', '500 meters'],
    correct: 1,
    difficulty: 'medium',
    coins: 5,
  },
  {
    id: 9,
    category: 'Networking Basics',
    question: 'What does MAC stand for in networking?',
    choices: ['Machine Address Code', 'Media Access Control', 'Multiple Access Channel', 'Master Access Certificate'],
    correct: 1,
    difficulty: 'easy',
    coins: 5,
  },
  {
    id: 10,
    category: 'Security',
    question: 'Which port does HTTPS use by default?',
    choices: ['80', '8443', '443', '22'],
    correct: 2,
    difficulty: 'easy',
    coins: 5,
  },
  {
    id: 11,
    category: 'OSI Model',
    question: 'Which OSI layer is responsible for routing packets between networks?',
    choices: ['Layer 2 – Data Link', 'Layer 3 – Network', 'Layer 4 – Transport', 'Layer 1 – Physical'],
    correct: 1,
    difficulty: 'medium',
    coins: 5,
  },
  {
    id: 12,
    category: 'Wi-Fi',
    question: 'What does SSID stand for?',
    choices: ['Secure Signal ID', 'Service Set Identifier', 'System Signal Interface Device', 'Station Subnet ID'],
    correct: 1,
    difficulty: 'easy',
    coins: 5,
  },
  {
    id: 13,
    category: 'Networking Basics',
    question: 'What is the primary function of a default gateway?',
    choices: [
      'Assign IP addresses automatically',
      'Block unauthorized traffic',
      'Forward traffic from the local network to external networks',
      'Translate domain names to IP addresses',
    ],
    correct: 2,
    difficulty: 'medium',
    coins: 5,
  },
  {
    id: 14,
    category: 'Protocols',
    question: 'What does TTL stand for in networking?',
    choices: ['Total Transfer Limit', 'Time To Live', 'Transfer Terminal Link', 'Tunnel Transport Layer'],
    correct: 1,
    difficulty: 'medium',
    coins: 5,
  },
  {
    id: 15,
    category: 'Protocols',
    question: 'Which protocol does the ping command use?',
    choices: ['TCP', 'UDP', 'ICMP', 'ARP'],
    correct: 2,
    difficulty: 'medium',
    coins: 5,
  },
  {
    id: 16,
    category: 'Security',
    question: 'What is a firewall primarily used for?',
    choices: [
      'Speeding up internet connections',
      'Filtering network traffic based on rules',
      'Translating IP addresses',
      'Assigning MAC addresses',
    ],
    correct: 1,
    difficulty: 'easy',
    coins: 5,
  },
  {
    id: 17,
    category: 'Subnetting',
    question: 'How many usable host addresses does a /30 subnet provide?',
    choices: ['1', '2', '4', '6'],
    correct: 1,
    difficulty: 'hard',
    coins: 8,
  },
  {
    id: 18,
    category: 'Protocols',
    question: 'Which protocol is used to securely transfer files over SSH?',
    choices: ['FTP', 'TFTP', 'SFTP', 'HTTP'],
    correct: 2,
    difficulty: 'medium',
    coins: 5,
  },
  {
    id: 19,
    category: 'OSI Model',
    question: 'Which device operates at OSI Layer 2 (Data Link)?',
    choices: ['Router', 'Hub', 'Switch', 'Modem'],
    correct: 2,
    difficulty: 'medium',
    coins: 5,
  },
  {
    id: 20,
    category: 'Networking Basics',
    question: 'What is the loopback IP address?',
    choices: ['192.168.1.1', '10.0.0.1', '127.0.0.1', '0.0.0.0'],
    correct: 2,
    difficulty: 'easy',
    coins: 5,
  },
];

// Shuffle the questions for each game
export function shuffleQuestions() {
  return [...QUESTIONS].sort(() => Math.random() - 0.5);
}
